/** @type {import('tailwindcss').Config} */
module.exports = {
    darkMode: "class",
    content: ["./*.html", "./products/*.html", "./js/*.js"],
    theme: {
        extend: {
            colors: {
                "on-tertiary-fixed-variant": "#683c00",
                "on-tertiary": "#492900",
                "tertiary": "#ffffff",
                "tertiary-container": "#ffdcbc",
                "surface-container": "#f1f1f1",
                "error": "#ba1a1a",
                "on-secondary-fixed-variant": "#474746",
                "secondary-container": "#e0e0e0",
                "error-container": "#ffdad6",
                "tertiary-fixed-dim": "#ffb86c",
                "on-secondary": "#ffffff",
                "inverse-primary": "#cdcd00",
                "on-primary": "#000000",
                "primary-fixed-dim": "#cdcd00",
                "surface": "#ffffff",
                "surface-container-high": "#e8e8e8",
                "primary-fixed": "#cdcd00",
                "surface-dim": "#dedada",
                "on-secondary-container": "#1c1b1b",
                "background": "#ffffff",
                "on-tertiary-container": "#2c1600",
                "outline-variant": "#c9c8aa",
                "tertiary-fixed": "#ffdcbc",
                "surface-container-lowest": "#ffffff",
                "surface-container-low": "#f8f8f8",
                "on-tertiary-fixed": "#2c1600",
                "on-surface": "#1c1b1b",
                "on-surface-variant": "#484831",
                "on-error-container": "#410002",
                "on-primary-fixed": "#1d1d00",
                "on-error": "#ffffff",
                "on-primary-container": "#1d1d00",
                "surface-container-highest": "#e2e2e2",
                "primary-container": "#ffff00",
                "on-primary-fixed-variant": "#494900",
                "on-secondary-fixed": "#1c1b1b",
                "inverse-on-surface": "#f4f0ef",
                "surface-variant": "#e5e3d2",
                "primary": "#000000",
                "secondary-fixed": "#474746",
                "outline": "#79785d",
                "surface-bright": "#fcf9f8",
                "secondary": "#5e5e5e",
                "secondary-fixed-dim": "#5e5e5e",
                "inverse-surface": "#313030",
                "surface-tint": "#626200",
                "on-background": "#1c1b1b"
            },
            fontFamily: {
                "headline": ["Space Grotesk", "sans-serif"],
                "body": ["Inter", "sans-serif"],
                "label": ["Inter", "sans-serif"]
            },
            borderRadius: { "DEFAULT": "0.125rem", "lg": "0.25rem", "xl": "0.5rem", "full": "0.75rem" },
        },
    },
    plugins: [
        require('@tailwindcss/container-queries'),
    ],
}
